### ISSUE TITLE
Access to custom endpoints

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/api-wrapper#11]
Currently, `.in()` is used to select a collection, appending `version` and `database` to the query URL. If no database is provided, the URL will contain `undefined` in its place.

Since `database` is omitted from URLs of custom endpoints, we need to find a way to remove it from the generated query URL in certain circumstances. 

**Option 1:** Add another selector method as an alternative to `.in()` — something like `.inEndpoint()` or `.fromEndpoint()`.

**Option 2:** Make `.in()` omit database from the URL if no `database` option is provided. This would solve the issue of custom endpoints not being supported, but does mean that a config with `database` defined can't be used to access custom endpoints (one thing shouldn't affect the other).

**Option 3:** Add a second parameter to `.in()`, defining whether to use `database`. In that case, one could access a `foo` custom endpoint by using `.in(foo, false)`, or similar. Not sure if clear enough.

In any case, we should limit the functionality available when using custom endpoints, perhaps to just using `.find()`, as I don't think it's sensible to allow documents to be modified via custom endpoints.

@mdahlstrand feel free to share any details I might have missed.

**Comment by jimlambie** [comment]
I prefer option 1, `.fromEndpoint()`

**Comment by eduardoboucas** [comment]
Closed via #15.
