### ISSUE TITLE
Unable to delete by ID

### ISSUE THREAD

**Issue by mingard** [dadi/api-wrapper#30]
Since release 1.4.0 the following **DELETE** query has stopped working. The response suggests that the action has been successful. 

```JSON
{"query": {"_id": {
        "$in": [
          "583c538a3ee2aed7101c55c1s"
        ]
      }
}}```

**Comment by eduardoboucas** [comment]
Issue is not in API wrapper. Closing in favour of https://github.com/dadi/api/issues/158
