### ISSUE TITLE
api-wrapper logs using the development environment

### ISSUE THREAD

**Issue by fra967** [dadi/api-wrapper#33]
api-wrapper, when used inside publish (which runs with env NODE_ENV=production ) logs into api-wrapper.development.log

**Comment by eduardoboucas** [comment]
@jimlambie [This](https://github.com/dadi/api-wrapper/blob/master/index.js#L25-L31) is how API wrapper is using DADI Logger. Do we need to pass information about the environment to it? Do we have a way to?

**Comment by jimlambie** [comment]
the short answer is "I don't know." 

Let me ask another one - what do we need to log in API Wrapper?

**Comment by fra967** [comment]
we probably don't need to log anything; if we need to troubleshoot some error, we could look in the api log, right?

**Comment by jimlambie** [comment]
True. How about we add the debug package so if there's a real problem we can run the app with debugging on?

**Comment by fra967** [comment]
ok for me, and we disable any logging otherwise

**Comment by eduardoboucas** [comment]
We do have a `debug` flag in the constructor of API wrapper. I can change the logging function to only do something if that flag is enabled.

**Comment by adamkdean** [comment]
I agree with Jim on this one. Using debug is a great way to control how noisy a service is. Especially when you can do wildcards, `DEBUG=dadi:*` etc.
