### ISSUE TITLE
API-wrapper errors are not captured 

### ISSUE THREAD

**Issue by fra967** [dadi/api-wrapper#38]
In Publish we are currently bound to api-wrapper 1.3.0

Whenever there is an error with the API call, the error triggers another error oat this line
https://github.com/dadi/api-wrapper/blob/v1.3.0/lib/helpers.js#L138
due to a missing check on err.response headers

```
{"message":"Cannot read property 'indexOf' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'indexOf' of undefined\n    at authenticatedRequest.catch.err (/dadi/publish/node_modules/@dadi/api-wrapper/lib/helpers.js:138:53)
```

we need to capture these errors while troubleshooting other issues, and it's just matter of  adding a defensive check on err.response and pass its value to this.logger.error

what we will also need is a new release (1.3.1) with just this change

**Comment by jimlambie** [comment]
I figured you were pinned to a certain release, as this is fixed in latest. I'll get this done asap

**Comment by jimlambie** [comment]
Resolved by https://github.com/dadi/api-wrapper/tree/1.3.x and NPM release `@dadi/api-wrapper@1.3.1`
